baseURL = "https://example.com/"
languageCode = "en-us"
title = "Jeongwoon Jeong"
theme = "hugo-resume"

[params]
    firstName = "Jeongwoon"
    lastName = "Jeong"
    address = "Iowa City, IA"
    phone = "1-315-450-9732"
    contactNote = "Dev Tools Engineer"
    profileImage = "img/profile3.jpg"
    email = "jeongwoon-jeong@uiowa.edu"
    description = "Software Platform Engineer with experience leveraging agile, DevOps, and CI/CD to manage large scale distributed platforms both on prem and in public cloud."
    favicon = "images/favicon.ico"
    # what sections
    showSkills = true
    showProjects = true
    showOpenSource = true
    showPublications = true
    showExperience = true
    showEducation = true

    showQr = true

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/edwardwebb/"


[[params.handles]]
    name = "GitHub"
    link = "https://github.com/eddiewebb/"

[[params.handles]]
    name = "Bitbucket"
    link = "https://bitbucket.org/eddiewebb/"

[[params.handles]]
    name = "Stack Overflow"
    link = "https://stackoverflow.com/users/story/82880"
    icon = "stack-overflow"

[[params.handles]]
    name = "Keybase"
    link = "https://keybase.io/edwardawebb"
    icon = "key"

[params.google.analytics]
    trackerID = "XX-123446-01"
